parkkeeper:
  image: telminov/park-keeper
  volumes:
    - ../django-park-keeper/parkkeeper/:/usr/local/lib/python3.5/site-packages/parkkeeper/
    - ../park-worker-base/parkworker/:/usr/local/lib/python3.5/site-packages/parkworker/
    - .:/opt/park-keeper/
  command:  bash -c "cd /opt/park-keeper/; cp supervisor/dev.conf /etc/supervisor/conf.d/park-keeper.conf; supervisord"
  ports:
    - 8080:8080
    - 8081:8081
    - 5548:5548
    - 5549:5549
    - 5550:5550
    - 5551:5551
    - 5552:5552
  external_links:
    - mongo3
    - mysql

parkworker2:
  image: telminov/park-worker-p2
  command:  bash -c "cd /opt/park-worker-p2/parkworker2; python bin/start_workers.py"
  volumes:
    - ../park-worker-base/parkworker/:/usr/local/lib/python2.7/dist-packages/parkworker/
    - ../park-worker-p2/:/opt/park-worker-p2/
  links:
    - parkkeeper

parkworker3:
  image: telminov/park-worker-p3
  command:  bash -c "cd /opt/park-worker-p3/parkworker3; python3 bin/start_workers.py"
  volumes:
    - ../park-worker-base/parkworker/:/usr/local/lib/python3.5/site-packages/parkworker/
    - ../park-worker-p3/:/opt/park-worker-p3/
  links:
    - parkkeeper
